Script started on Mon 09 Mar 2015 05:03:13 PM PDT
[01;32mgyosh@gyosh-MBP[01;34m ~/Documents/rshell $[00m ls
[0m[01;34mbin[0m  LICENSE  Makefile  README.md  [01;34msrc[0m  [01;34mtests[0m
[01;32mgyosh@gyosh-MBP[01;34m ~/Documents/rshell $[00m make
g++ -std=c++11 src/rshell.cpp -o bin/rshell 
g++ -std=c++11 src/ls.cpp -o bin/ls 
[01;32mgyosh@gyosh-MBP[01;34m ~/Documents/rshell $[00m bin/rshell
gyosh@gyosh-/home/gyosh/Documents/rshell$ ls
bin  LICENSE  Makefile	README.md  src	tests
gyosh@gyosh-/home/gyosh/Documents/rshell$ cd bin
gyosh@gyosh-/home/gyosh/Documents/rshell/bin$ ls
ls  rshell  
gyosh@gyosh-/home/gyosh/Documents/rshell/bin$ ./ls
ls  rshell  
gyosh@gyosh-/home/gyosh/Documents/rshell/bin$ #myls
gyosh@gyosh-/home/gyosh/Documents/rshell/bin$ ./ls    cd ..
gyosh@gyosh-/home/gyosh/Documents/rshell$ ./bin/ls -a
.  ..  .git  bin  LICENSE  Makefile  README.md  src  tests  
gyosh@gyosh-/home/gyosh/Documents/rshell$ ./bin/ls -l
total 40
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 17:03 bin
-rw-r--r-- 1 gyosh gyosh  18027 Feb  2 17:22 LICENSE
-rw-r--r-- 1 gyosh gyosh    224 Feb 23 00:10 Makefile
-rw-r--r-- 1 gyosh gyosh   1075 Feb 23 00:10 README.md
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 17:02 src
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 17:03 tests
gyosh@gyosh-/home/gyosh/Documents/rshell$ ./bin/ls -R
.:
bin  LICENSE  Makefile  README.md  src  tests  

./bin:
ls  rshell  

./src:
ls.cpp  rshell.cpp  rshell.h  

./tests:
ls.script  piping.script  regrade.script  rshell.script  signals.script  

gyosh@gyosh-/home/gyosh/Documents/rshell$ ./bin. /ls /
bin  boot  cdrom  dev  etc  home  initrd.img  lib  lib32  lib64  libx32  lost+found  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var  vmlinuz  
gyosh@gyosh-/home/gyosh/Documents/rshell$ ./bin/. ls / -a
.  ..  bin  boot  cdrom  dev  etc  home  initrd.img  lib  lib32  lib64  libx32  lost+found  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var  vmlinuz  
gyosh@gyosh-/home/gyosh/Documents/rshell$ ./bin/ls - / -l
total 34080
drwxr-xr-x 2 root root   4096 Jan 28 20:46 bin
drwxr-xr-x 3 root root   4096 Jan 28 23:08 boot
drwxr-xr-x 2 root root   4096 Jan 28 18:47 cdrom
drwxr-xr-x 17 root root   4320 Mar  9 16:54 dev
drwxr-xr-x 146 root root  12288 Mar  9 16:58 etc
drwxr-xr-x 3 root root   4096 Jan 28 18:47 home
-rw-r--r-- 1 root root28975226 Jan 28 23:08 initrd.img
drwxr-xr-x 25 root root   4096 Jan 28 20:10 lib
drwxr-xr-x 2 root root   4096 Jan 28 20:10 lib32
drwxr-xr-x 2 root root   4096 Jan 28 20:10 lib64
drwxr-xr-x 2 root root   4096 Jan 28 20:10 libx32
drwx------ 2 root root  16384 Jan 28 18:44 lost+found
drwxr-xr-x 6 root root   4096 Feb 18 22:23 media
drwxr-xr-x 3 root root   4096 Jan 28 22:46 mnt
drwxr-xr-x 4 root root   4096 Feb  1 01:23 opt
dr-xr-xr-x 183 root root      0 Mar  9 16:54 proc
drwx------ 9 root root   4096 Jan 28 23:23 root
drwxr-xr-x 25 root root    800 Mar  9 16:55 run
drwxr-xr-x 2 root root  12288 Jan 28 20:45 sbin
drwxr-xr-x 2 root root   4096 Nov 26 14:12 srv
dr-xr-xr-x 13 root root      0 Mar  9 16:54 sys
drwxrwxrwx 10 root root   4096 Mar  9 17:03 tmp
drwxr-xr-x 12 root root   4096 Jan 28 20:10 usr
drwxr-xr-x 11 root root   4096 Nov 26 14:48 var
-rw-r--r-- 1 root root5808832 Nov 26 14:54 vmlinuz
gyosh@gyosh-/home/gyosh/Documents/rshell$ ./bion/   n/ls /-  -R
/:
bin  boot  cdrom  dev  etc  home  initrd.img  lib  lib32  lib64  libx32  lost+found  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var  vmlinuz  

//bin:
stat failed: No such file or directory
bash  gyosh@gyosh-/home/gyosh/Documents/rshell$ ./bin/ls -al
total 52
drwxr-xr-x 6 gyosh gyosh   4096 Mar  9 17:03 .
drwxr-xr-x 9 gyosh gyosh   4096 Mar  9 14:08 ..
drwxr-xr-x 8 gyosh gyosh   4096 Mar  9 14:27 .git
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 17:03 bin
-rw-r--r-- 1 gyosh gyosh  18027 Feb  2 17:22 LICENSE
-rw-r--r-- 1 gyosh gyosh    224 Feb 23 00:10 Makefile
-rw-r--r-- 1 gyosh gyosh   1075 Feb 23 00:10 README.md
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 17:02 src
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 17:03 tests
gyosh@gyosh-/home/gyosh/Documents/rshell$ ./bin/ls -al
total 52
drwxr-xr-x 6 gyosh gyosh   4096 Mar  9 17:03 .
drwxr-xr-x 9 gyosh gyosh   4096 Mar  9 14:08 ..
drwxr-xr-x 8 gyosh gyosh   4096 Mar  9 14:27 .git
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 17:03 bin
-rw-r--r-- 1 gyosh gyosh  18027 Feb  2 17:22 LICENSE
-rw-r--r-- 1 gyosh gyosh    224 Feb 23 00:10 Makefile
-rw-r--r-- 1 gyosh gyosh   1075 Feb 23 00:10 README.md
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 17:02 src
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 17:03 tests
gyosh@gyosh-/home/gyosh/Documents/rshell$ ./bin/ls -alR
.:
total 52
drwxr-xr-x 6 gyosh gyosh   4096 Mar  9 17:03 .
drwxr-xr-x 9 gyosh gyosh   4096 Mar  9 14:08 ..
drwxr-xr-x 8 gyosh gyosh   4096 Mar  9 14:27 .git
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 17:03 bin
-rw-r--r-- 1 gyosh gyosh  18027 Feb  2 17:22 LICENSE
-rw-r--r-- 1 gyosh gyosh    224 Feb 23 00:10 Makefile
-rw-r--r-- 1 gyosh gyosh   1075 Feb 23 00:10 README.md
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 17:02 src
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 17:03 tests

./.git:
total 64
drwxr-xr-x 8 gyosh gyosh   4096 Mar  9 14:27 .
drwxr-xr-x 6 gyosh gyosh   4096 Mar  9 17:03 ..
drwxr-xr-x 2 gyosh gyosh   4096 Feb  2 17:22 branches
-rw-r--r-- 1 gyosh gyosh     14 Mar  9 14:25 COMMIT_EDITMSG
-rw-r--r-- 1 gyosh gyosh    197 Mar  9 14:27 config
-rw-r--r-- 1 gyosh gyosh     73 Feb  2 17:22 description
-rw-r--r-- 1 gyosh gyosh    203 Feb 17 20:08 FETCH_HEAD
-rw-r--r-- 1 gyosh gyosh     23 Mar  9 14:27 HEAD
drwxr-xr-x 2 gyosh gyosh   4096 Feb  2 17:22 hooks
-rw-r--r-- 1 gyosh gyosh    920 Mar  9 14:27 index
drwxr-xr-x 2 gyosh gyosh   4096 Feb  2 17:22 info
drwxr-xr-x 3 gyosh gyosh   4096 Feb  2 17:22 logs
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 objects
-rw-r--r-- 1 gyosh gyosh     41 Mar  9 13:53 ORIG_HEAD
-rw-r--r-- 1 gyosh gyosh    173 Feb  2 17:22 packed-refs
drwxr-xr-x 5 gyosh gyosh   4096 Feb  2 17:22 refs

./bin:
total 156
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 17:03 .
drwxr-xr-x 6 gyosh gyosh   4096 Mar  9 17:03 ..
-rwxr-xr-x 1 gyosh gyosh  55930 Mar  9 17:03 ls
-rwxr-xr-x 1 gyosh gyosh  94135 Mar  9 17:03 rshell

./src:
total 68
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 17:02 .
drwxr-xr-x 6 gyosh gyosh   4096 Mar  9 17:03 ..
-rw-r--r-- 1 gyosh gyosh  16384 Mar  9 17:02 .ls.cpp.swp
-rw-r--r-- 1 gyosh gyosh  20480 Mar  9 17:01 .rshell.h.swp
-rw-r--r-- 1 gyosh gyosh   5461 Mar  9 17:02 ls.cpp
-rw-r--r-- 1 gyosh gyosh   2115 Mar  9 13:52 rshell.cpp
-rw-r--r-- 1 gyosh gyosh   9246 Mar  9 17:01 rshell.h

./tests:
total 300
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 17:03 .
drwxr-xr-x 6 gyosh gyosh   4096 Mar  9 17:03 ..
-rw-r--r-- 1 gyosh gyosh   4096 Mar  9 17:04 ls.script
-rw-r--r-- 1 gyosh gyosh   1515 Feb 23 00:10 piping.script
-rw-r--r-- 1 gyosh gyosh 277245 Mar  9 14:19 regrade.script
-rw-r--r-- 1 gyosh gyosh   2423 Feb 23 00:10 rshell.script
-rw-r--r-- 1 gyosh gyosh   3433 Mar  9 14:24 signals.script

./.git/branches:
total 8
drwxr-xr-x 2 gyosh gyosh   4096 Feb  2 17:22 .
drwxr-xr-x 8 gyosh gyosh   4096 Mar  9 14:27 ..

./.git/hooks:
total 48
drwxr-xr-x 2 gyosh gyosh   4096 Feb  2 17:22 .
drwxr-xr-x 8 gyosh gyosh   4096 Mar  9 14:27 ..
-rwxr-xr-x 1 gyosh gyosh    452 Feb  2 17:22 applypatch-msg.sample
-rwxr-xr-x 1 gyosh gyosh    896 Feb  2 17:22 commit-msg.sample
-rwxr-xr-x 1 gyosh gyosh    189 Feb  2 17:22 post-update.sample
-rwxr-xr-x 1 gyosh gyosh    398 Feb  2 17:22 pre-applypatch.sample
-rwxr-xr-x 1 gyosh gyosh   1642 Feb  2 17:22 pre-commit.sample
-rwxr-xr-x 1 gyosh gyosh   1352 Feb  2 17:22 pre-push.sample
-rwxr-xr-x 1 gyosh gyosh   4898 Feb  2 17:22 pre-rebase.sample
-rwxr-xr-x 1 gyosh gyosh   1239 Feb  2 17:22 prepare-commit-msg.sample
-rwxr-xr-x 1 gyosh gyosh   3611 Feb  2 17:22 update.sample

./.git/info:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb  2 17:22 .
drwxr-xr-x 8 gyosh gyosh   4096 Mar  9 14:27 ..
-rw-r--r-- 1 gyosh gyosh    240 Feb  2 17:22 exclude

./.git/logs:
total 20
drwxr-xr-x 3 gyosh gyosh   4096 Feb  2 17:22 .
drwxr-xr-x 8 gyosh gyosh   4096 Mar  9 14:27 ..
-rw-r--r-- 1 gyosh gyosh   5255 Mar  9 14:27 HEAD
drwxr-xr-x 4 gyosh gyosh   4096 Feb  2 17:22 refs

./.git/objects:
total 396
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 .
drwxr-xr-x 8 gyosh gyosh   4096 Mar  9 14:27 ..
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 05
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 07
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 00:03 09
drwxr-xr-x 2 gyosh gyosh   4096 Feb 22 23:18 0b
drwxr-xr-x 2 gyosh gyosh   4096 Feb 26 00:05 0e
drwxr-xr-x 2 gyosh gyosh   4096 Feb 22 23:55 0f
drwxr-xr-x 2 gyosh gyosh   4096 Feb 23 00:06 10
drwxr-xr-x 2 gyosh gyosh   4096 Feb 23 00:04 11
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 14:25 16
drwxr-xr-x 2 gyosh gyosh   4096 Feb  8 11:49 1a
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:46 1c
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 1d
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:48 1f
drwxr-xr-x 2 gyosh gyosh   4096 Feb 21 20:01 22
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:35 24
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:55 25
drwxr-xr-x 2 gyosh gyosh   4096 Feb 23 00:04 27
drwxr-xr-x 2 gyosh gyosh   4096 Feb 22 23:55 2b
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 00:02 2c
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 2f
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 30
drwxr-xr-x 2 gyosh gyosh   4096 Feb 22 23:18 33
drwxr-xr-x 2 gyosh gyosh   4096 Feb 22 23:55 39
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 00:03 3a
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 14:25 41
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 44
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:34 45
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:46 48
drwxr-xr-x 2 gyosh gyosh   4096 Feb 22 23:18 4b
drwxr-xr-x 2 gyosh gyosh   4096 Feb 22 23:58 4d
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:47 4e
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 51
drwxr-xr-x 2 gyosh gyosh   4096 Feb 22 23:54 52
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:52 56
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 00:02 57
drwxr-xr-x 2 gyosh gyosh   4096 Feb  8 11:49 5c
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 5d
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 5e
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 14:25 5f
drwxr-xr-x 2 gyosh gyosh   4096 Feb 23 00:10 60
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:47 64
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 66
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 68
drwxr-xr-x 2 gyosh gyosh   4096 Feb  8 11:48 6b
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 6c
drwxr-xr-x 2 gyosh gyosh   4096 Feb 23 00:04 6d
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 6e
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:46 76
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 7c
drwxr-xr-x 2 gyosh gyosh   4096 Feb  8 11:48 7f
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 81
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 00:02 83
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 85
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:36 8c
drwxr-xr-x 2 gyosh gyosh   4096 Feb 23 00:06 8e
drwxr-xr-x 2 gyosh gyosh   4096 Feb 22 23:55 90
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 14:24 91
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 00:04 95
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 96
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:34 98
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 00:03 9c
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 9e
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 14:25 9f
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:46 a2
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 a6
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:55 a9
drwxr-xr-x 2 gyosh gyosh   4096 Feb 21 19:52 ae
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:55 b0
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 b1
drwxr-xr-x 2 gyosh gyosh   4096 Feb 23 00:04 b3
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 ba
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 bb
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:46 bd
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:35 bf
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 c1
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:45 c4
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:38 c5
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:34 c8
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:46 cb
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:46 cc
drwxr-xr-x 2 gyosh gyosh   4096 Feb 23 00:06 d0
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 d6
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 d7
drwxr-xr-x 2 gyosh gyosh   4096 Feb  8 11:49 e3
drwxr-xr-x 2 gyosh gyosh   4096 Feb  8 11:48 e4
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:35 e5
drwxr-xr-x 2 gyosh gyosh   4096 Feb  8 11:48 e8
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 e9
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 ed
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:55 f8
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 f9
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 fb
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:46 fc
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:46 fe
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 ff
drwxr-xr-x 2 gyosh gyosh   4096 Feb  2 17:22 info
drwxr-xr-x 2 gyosh gyosh   4096 Feb  2 17:22 pack

./.git/refs:
total 20
drwxr-xr-x 5 gyosh gyosh   4096 Feb  2 17:22 .
drwxr-xr-x 8 gyosh gyosh   4096 Mar  9 14:27 ..
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 14:27 heads
drwxr-xr-x 3 gyosh gyosh   4096 Feb  2 17:22 remotes
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 14:24 tags

./.git/logs/refs:
total 16
drwxr-xr-x 4 gyosh gyosh   4096 Feb  2 17:22 .
drwxr-xr-x 3 gyosh gyosh   4096 Feb  2 17:22 ..
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 14:27 heads
drwxr-xr-x 3 gyosh gyosh   4096 Feb  2 17:22 remotes

./.git/objects/05:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    784 Feb 17 20:08 9a8204ba5e18deebf185e8bab6a417baa245e2

./.git/objects/07:
total 24
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh  13870 Feb 17 20:08 795c0f63ada5a1aedb8c4f8b7bdf187e0013fe

./.git/objects/09:
total 16
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 00:03 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    108 Mar  9 00:03 c99118330110e29c2f91920924f7c22def651a
-r--r--r-- 1 gyosh gyosh    185 Feb 17 20:08 cd5de3a47b877c22d72759218f8ebeac30a9f1

./.git/objects/0b:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 22 23:18 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    162 Feb 22 23:18 189a938bc2710ca195238297f50e9fe2a8d5a7

./.git/objects/0e:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 26 00:05 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    185 Feb 26 00:05 5cc839abf841325ad6f2394221d819ca265424

./.git/objects/0f:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 22 23:55 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh     85 Feb 22 23:55 92327e7f39675ae5426ec3d1121e5aafdbd227

./.git/objects/10:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 23 00:06 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh     82 Feb 23 00:06 c6cf6b4ab227eca1a46ff73beb9a0af82d6f24

./.git/objects/11:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 23 00:04 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh   3143 Feb 23 00:04 40c9451da1d26a6348be259818c2927bb124b0

./.git/objects/16:
total 16
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 14:25 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    176 Mar  9 14:25 e598bcfb288905eaa9987e50cd53e5904e6c6d
-r--r--r-- 1 gyosh gyosh    178 Mar  9 14:25 f538ac4983ebc9707a6dc70f38080cba82b1c6

./.git/objects/1a:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb  8 11:49 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    186 Feb  8 11:49 9030b7328135ed2f8794c14df997e60abcf625

./.git/objects/1c:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:46 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    148 Mar  9 13:46 1df43021902b8765126507c4f1c1eec16f1652

./.git/objects/1d:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh   1543 Feb 17 20:08 6d9cab3b7c7d59d9cca1d5e7883f6f228a9bed

./.git/objects/1f:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:48 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    134 Mar  9 13:48 127881006c7b98588028aa3bee7fd1a4fb187a

./.git/objects/22:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 21 20:01 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    130 Feb 21 20:01 11125650caca0362695b5bfbaa34c8004794c7

./.git/objects/24:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:35 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    177 Mar  9 13:35 f6ef82c711272b5f25dc4941d44b71a3bacbb1

./.git/objects/25:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:55 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    128 Mar  9 13:55 c7713db91b48029af7986c774eaec9083779a4

./.git/objects/27:
total 16
drwxr-xr-x 2 gyosh gyosh   4096 Feb 23 00:04 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh   4381 Feb 23 00:04 3dae8e328ecf696941f5a05b17f1b95757ccdc

./.git/objects/2b:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 22 23:55 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh     82 Feb 22 23:55 24f442e96bd730897ae6d58223b4473c823d23

./.git/objects/2c:
total 16
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 00:02 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh   1810 Feb 17 20:08 0fd6cfba1525b357944baedffd9a61ebcd1efd
-r--r--r-- 1 gyosh gyosh   2955 Mar  9 00:02 b5243ce5568ece9a547d98228764b6110e5f40

./.git/objects/2f:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    172 Feb 17 20:08 7596ec2f711d84bd67f91959c40e84cd47d495

./.git/objects/30:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    115 Feb 17 20:08 3bc39e9a915193b5ff91bbce89cb0512775714

./.git/objects/33:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 22 23:18 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh     82 Feb 22 23:18 3438eb3d337586e627ce3f3dea44fc78b767a9

./.git/objects/39:
total 16
drwxr-xr-x 2 gyosh gyosh   4096 Feb 22 23:55 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    115 Feb 17 20:08 1c70cb39430f6b85be99fe88e81601c73b1ce4
-r--r--r-- 1 gyosh gyosh    177 Feb 22 23:55 cabfa53b9c57601d15ad87404b02d16bfe1ab9

./.git/objects/3a:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 00:03 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    159 Mar  9 00:03 243b0a1b209043320f9587982bc61a23504d41

./.git/objects/41:
total 68
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 14:25 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh  58197 Mar  9 14:25 7424114257cf96568245a9037ae4c9ec4934ff

./.git/objects/44:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    497 Feb 17 20:08 632c36d076d24904315b66990b8c2f7ee1e320

./.git/objects/45:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:34 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    941 Mar  9 13:34 f444c8babb03b0945a2aa3c40682b72e83238f

./.git/objects/48:
total 16
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:46 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    164 Mar  9 13:46 495ae6ed0ef6af2cb0bddfd0f6897ebe4732ed
-r--r--r-- 1 gyosh gyosh   2027 Mar  9 00:02 79e8a29fd0422d1df250c20aa9711849e8db0d

./.git/objects/4b:
total 16
drwxr-xr-x 2 gyosh gyosh   4096 Feb 22 23:18 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh   5795 Feb 22 23:18 6e0cc4514a826559a9b6487350c3a0f55329dd

./.git/objects/4d:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 22 23:58 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    624 Feb 22 23:58 0113bdc1403b0c695f4d0e8d2c8f7ac76ec833

./.git/objects/4e:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:47 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    177 Mar  9 13:47 0987ddee644cf10032ab4963db763ef680932b

./.git/objects/51:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    174 Feb 17 20:08 4430c4c6073d129408823bc808d337c551c1da

./.git/objects/52:
total 16
drwxr-xr-x 2 gyosh gyosh   4096 Feb 22 23:54 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh   3128 Feb 22 23:54 8d3d4503bcd436673ef8e3f1be1af2fc8b8a68
-r--r--r-- 1 gyosh gyosh    115 Feb 17 20:08 d2a08a6c2f1e46d84c8d2f61ee382d0ce7f610

./.git/objects/56:
total 32
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:52 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh  20393 Mar  9 13:34 464ad48d06abde179a7a7b38a013d4eb8f7839
-r--r--r-- 1 gyosh gyosh    925 Mar  9 13:52 62701037e5af635310a6528f82ee54549d685b

./.git/objects/57:
total 16
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 00:02 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh   1024 Mar  9 00:02 59ca6d7b009737defcd0dc7209b3390077ad27
-r--r--r-- 1 gyosh gyosh    499 Feb 23 00:04 8b811f105b02ce2fb6da6b5e94e1dcb01a3771

./.git/objects/5c:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb  8 11:49 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    157 Feb  8 11:49 9a61df154a6ba13d39578f730a2a26a5d4f564

./.git/objects/5d:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    163 Feb 17 20:08 d9a19ec7fed694a9870fa68903879498ebb48a

./.git/objects/5e:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    185 Feb 17 20:08 64cb3e57ea27a1bc7dee84173b392861acff78

./.git/objects/5f:
total 20
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 14:25 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    157 Feb 17 20:08 412dc36a6922c51c343b1e98249ed28b3ac6f8
-r--r--r-- 1 gyosh gyosh    108 Mar  9 13:47 80bb9b0d9780157c6ade2bcbfdc8c89890b0ba
-r--r--r-- 1 gyosh gyosh    156 Mar  9 14:25 f49cf5d6e6ada8d3732e3e4deba1f2945806a7

./.git/objects/60:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 23 00:10 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    125 Feb 23 00:10 0721c6bca96e9c2987e6ac71bfc503e57b2ad3

./.git/objects/64:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:47 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    154 Mar  9 13:47 8b13943e947778bd6a1aaccec1d2b3a9a96c82

./.git/objects/66:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh   2453 Feb 17 20:08 cd8427d081b3f83a288bb9c3d98b8bd9628db2

./.git/objects/68:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh   1814 Feb 17 20:08 f7d30f23daf6c849b53af41cfb9c58ba593fb1

./.git/objects/6b:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb  8 11:48 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    198 Feb  8 11:48 83d48307cdf189a27005bd8fc13efa0aab721d

./.git/objects/6c:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    182 Feb 17 20:08 92b5b3c18e404aa43edf76a061d346b24047f2

./.git/objects/6d:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 23 00:04 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    115 Feb 23 00:04 b2f0dc4e8e26149af9a20d7cc8289d775c0496

./.git/objects/6e:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    185 Feb 17 20:08 57e7bf01febbaf8eb46f9d9caddee71d08b5d7

./.git/objects/76:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:46 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    203 Mar  9 13:46 0641aa1fd7e78f1192b02c186f9a8f8a7d1f1e

./.git/objects/7c:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    211 Feb 17 20:08 6e505fb133176aaca26fbb63bd3720e7902192

./.git/objects/7f:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb  8 11:48 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    160 Feb  8 11:48 09857d85e6e49b21cdd145a7e6a826d337e332

./.git/objects/81:
total 16
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh   1428 Feb 17 20:08 452697ebdc0f4bb2a53dbc54ed5ded8e75381f
-r--r--r-- 1 gyosh gyosh    773 Feb 17 20:08 f77c41f5b5c2ea284d4bce9296468a04cb20e8

./.git/objects/83:
total 16
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 00:02 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh   5090 Mar  9 00:02 3928410adb45abfff7b65bcfde7bc8cc09d696

./.git/objects/85:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    185 Feb 17 20:08 4bd625e132d006bbff7b552c91f1664d61e518

./.git/objects/8c:
total 20
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:36 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    125 Mar  9 13:36 1b8c45f78135c3f712ffc9e36a33c75f85ea81
-r--r--r-- 1 gyosh gyosh   3383 Mar  9 13:34 2a87a4e60a63ee779b511c834a4aa877ad1556
-r--r--r-- 1 gyosh gyosh    169 Feb 23 00:04 560b0b0032ae474ccf1fd940d4c6bc2704bab7

./.git/objects/8e:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 23 00:06 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    177 Feb 23 00:06 3060c6d893fc0df9f9c5f9bca226a1626a11f7

./.git/objects/90:
total 16
drwxr-xr-x 2 gyosh gyosh   4096 Feb 22 23:55 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    167 Feb 22 23:18 726cfe0255a0115b4a034843b1ee207f1a7604
-r--r--r-- 1 gyosh gyosh    178 Feb 22 23:55 fdd2cdd971b9a3c098a510a4f1fa66cdb2ed47

./.git/objects/91:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 14:24 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    124 Mar  9 14:24 16bc8fc494df2de70f7454e950c8b8f2ece223

./.git/objects/95:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 00:04 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    130 Mar  9 00:04 fac3e2c818d55b43afb4c939142d1dc29af76d

./.git/objects/96:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    158 Feb 17 20:08 740d40de9c7a6a85c08f707dfd4aff97627786

./.git/objects/98:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:34 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh     85 Mar  9 13:34 ba924f643c0af9e3576284aaa66e1c98413236

./.git/objects/9c:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 00:03 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    177 Mar  9 00:03 68a7404d24a44c1d5446fd261d2ef6345de83e

./.git/objects/9e:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    154 Feb 17 20:08 87cfe4650a90d7bfb996694cc048ad5f46c5fd

./.git/objects/9f:
total 16
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 14:25 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    341 Mar  9 00:02 c611fa9e9c6dd6974c5132b162bc9b4f6bfc37
-r--r--r-- 1 gyosh gyosh    882 Mar  9 14:25 e3333608314964b7b8b776a2127884c76f34e6

./.git/objects/a2:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:46 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    141 Mar  9 13:46 4d650730371cafc941a38da0271274bfddfd5a

./.git/objects/a6:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    167 Feb 17 20:08 5d3d3b35dfbec2dc5e736d990a64c51903a58f

./.git/objects/a9:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:55 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    177 Mar  9 13:55 dc48b46e95f5a134fcb0202d59b7368c2dcd62

./.git/objects/ae:
total 16
drwxr-xr-x 2 gyosh gyosh   4096 Feb 21 19:52 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    498 Feb 21 19:52 319f80d1f4c20a3b211580c4abe556062bdcfa
-r--r--r-- 1 gyosh gyosh    160 Feb 17 20:08 4c1e6560f5095f5a7153bda7e7263c103fb487

./.git/objects/b0:
total 20
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:55 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    155 Mar  9 13:55 27da8d14d53b9fa6f4560e059f95597ef5ac99
-r--r--r-- 1 gyosh gyosh    117 Feb 23 00:04 69d2b854989e8293b020d0ef95f34c48507f52
-r--r--r-- 1 gyosh gyosh    212 Feb 22 23:18 87cfa1789ebd3779cf66382d1871760b25ce93

./.git/objects/b1:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh   1819 Feb 17 20:08 d00c27353f6291071a3ca2ea19a0b0d2bdce34

./.git/objects/b3:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 23 00:04 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    177 Feb 23 00:04 3248c2574e77667a6ff4ed8302d8435261ab40

./.git/objects/ba:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    185 Feb 17 20:08 261b2d93e2f7aeb6a843fa9b724866f7fa9e5c

./.git/objects/bb:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh     82 Feb 17 20:08 ee33655c6772b801f043cb031fb7c8a986c266

./.git/objects/bd:
total 16
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:46 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh   1543 Feb 17 20:08 0aaa4e514ef044219d68e086c3b1c274489f79
-r--r--r-- 1 gyosh gyosh    554 Mar  9 13:46 a1ea9424b8f86975d151ca5625b42c7d3f4a76

./.git/objects/bf:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:35 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    108 Mar  9 13:35 1e8389a9e13f768d9250a345b1147a63943f76

./.git/objects/c1:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    450 Feb 17 20:08 777ba9c25c340716fe7f0ba7577b3fc684f631

./.git/objects/c4:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:45 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh   3105 Mar  9 13:45 7b05c5bdcfa058d4ba1e55d803b286cfb880dd

./.git/objects/c5:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:38 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh   3105 Mar  9 13:38 65c6b095e14c3f1cfe0a2e00e5c9a1e91a910d

./.git/objects/c8:
total 40
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:34 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh  31554 Mar  9 13:34 2ee6dcf550d486d665ffeda712d7a2fc4f269f

./.git/objects/cb:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:46 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh     76 Mar  9 13:46 eb547aff6a11869a28c05c8486532a3b616c28

./.git/objects/cc:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:46 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh   1383 Mar  9 13:46 a0edbb3f8a73974d583fb6469208fe9630b3a4

./.git/objects/d0:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 23 00:06 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    157 Feb 23 00:06 84c82d403c386e630b23588393f941c0da5fa2

./.git/objects/d6:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh     82 Feb 17 20:08 eb9be76d4d887a60c0a75bb1914c666c0e9ac3

./.git/objects/d7:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    185 Feb 17 20:08 df2a935bfbb71118832245bbcab80acc4df702

./.git/objects/e3:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb  8 11:49 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh     82 Feb  8 11:49 01ac92b6fbb9e3bf320901e6dd12828c91d7bf

./.git/objects/e4:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb  8 11:48 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    598 Feb  8 11:48 68ca2f599c9c2448924f2ac5bb142162ae3bc6

./.git/objects/e5:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:35 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    170 Mar  9 13:35 f3d9e2c107831c077dbc50c5af8532cae15c7b

./.git/objects/e8:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb  8 11:48 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    490 Feb  8 11:48 73440db23087130c223b8c77b46752f68e14f5

./.git/objects/e9:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh     82 Feb 17 20:08 16a1f527f40f4c223b8361a2729c5943d67ede

./.git/objects/ed:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh   2772 Feb 17 20:08 f052c47dcff9673d94e878349a15367f7d8c3b

./.git/objects/f8:
total 20
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:55 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh   3121 Feb 22 23:18 0f4a64b4b2b547e076f9f6bc8083db33447b2d
-r--r--r-- 1 gyosh gyosh    185 Feb 17 20:08 bfcb6735fcdedf99324a12f924855bb2a9651e
-r--r--r-- 1 gyosh gyosh    107 Mar  9 13:55 c06c7cefc7300a27280b43e3a3762f0290fbbc

./.git/objects/f9:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh     82 Feb 17 20:08 d88b1738341f5f8776f4277e5c6364f1136486

./.git/objects/fb:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh    212 Feb 17 20:08 896f173ca53289a3dade1ecaefed3dd835324e

./.git/objects/fc:
total 40
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:46 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh  31335 Mar  9 13:46 83653d163b2f24d22fb3505336808d85395828

./.git/objects/fe:
total 16
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 13:46 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh   1845 Mar  9 00:02 d434782b2047767dd63837f153f833a29fd289
-r--r--r-- 1 gyosh gyosh    948 Mar  9 13:46 f346a5f5ac96af42b28b1aacb0d4f91f3dffb7

./.git/objects/ff:
total 12
drwxr-xr-x 2 gyosh gyosh   4096 Feb 17 20:08 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh     82 Feb 17 20:08 4270ef5b46166604f85dabfe2a46ae50b0d811

./.git/objects/info:
total 8
drwxr-xr-x 2 gyosh gyosh   4096 Feb  2 17:22 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..

./.git/objects/pack:
total 88
drwxr-xr-x 2 gyosh gyosh   4096 Feb  2 17:22 .
drwxr-xr-x 99 gyosh gyosh   4096 Mar  9 14:25 ..
-r--r--r-- 1 gyosh gyosh   4292 Feb  2 17:22 pack-5e20ecec0181a2bf0deecba0233700a38c1a7d0a.idx
-r--r--r-- 1 gyosh gyosh  71581 Feb  2 17:22 pack-5e20ecec0181a2bf0deecba0233700a38c1a7d0a.pack

./.git/refs/heads:
total 16
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 14:27 .
drwxr-xr-x 5 gyosh gyosh   4096 Feb  2 17:22 ..
-rw-r--r-- 1 gyosh gyosh     41 Mar  9 14:27 master
-rw-r--r-- 1 gyosh gyosh     41 Mar  9 14:25 redirect

./.git/refs/remotes:
total 12
drwxr-xr-x 3 gyosh gyosh   4096 Feb  2 17:22 .
drwxr-xr-x 5 gyosh gyosh   4096 Feb  2 17:22 ..
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 14:27 origin

./.git/refs/tags:
total 16
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 14:24 .
drwxr-xr-x 5 gyosh gyosh   4096 Feb  2 17:22 ..
-rw-r--r-- 1 gyosh gyosh     41 Feb 23 00:10 hw2
-rw-r--r-- 1 gyosh gyosh     41 Mar  9 14:24 hw3

./.git/logs/refs/heads:
total 16
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 14:27 .
drwxr-xr-x 4 gyosh gyosh   4096 Feb  2 17:22 ..
-rw-r--r-- 1 gyosh gyosh    157 Mar  9 14:27 master
-rw-r--r-- 1 gyosh gyosh   1977 Mar  9 14:25 redirect

./.git/logs/refs/remotes:
total 12
drwxr-xr-x 3 gyosh gyosh   4096 Feb  2 17:22 .
drwxr-xr-x 4 gyosh gyosh   4096 Feb  2 17:22 ..
drwxr-xr-x 2 gyosh gyosh   4096 Feb 23 00:13 origin

./.git/refs/remotes/origin:
total 20
drwxr-xr-x 2 gyosh gyosh   4096 Mar  9 14:27 .
drwxr-xr-x 3 gyosh gyosh   4096 Feb  2 17:22 ..
-rw-r--r-- 1 gyosh gyosh     32 Feb  2 17:22 HEAD
-rw-r--r-- 1 gyosh gyosh     41 Mar  9 14:27 master
-rw-r--r-- 1 gyosh gyosh     41 Mar  9 14:27 redirect

./.git/logs/refs/remotes/origin:
total 20
drwxr-xr-x 2 gyosh gyosh   4096 Feb 23 00:13 .
drwxr-xr-x 3 gyosh gyosh   4096 Feb  2 17:22 ..
-rw-r--r-- 1 gyosh gyosh    178 Feb  2 17:22 HEAD
-rw-r--r-- 1 gyosh gyosh    587 Mar  9 14:27 master
-rw-r--r-- 1 gyosh gyosh    438 Mar  9 14:27 redirect

gyosh@gyosh-/home/gyosh/Documents/rshell$ ./bin/ls        exit
[01;32mgyosh@gyosh-MBP[01;34m ~/Documents/rshell $[00m ls
[0m[01;34mbin[0m  LICENSE  Makefile  README.md  [01;34msrc[0m  [01;34mtests[0m
[01;32mgyosh@gyosh-MBP[01;34m ~/Documents/rshell $[00m exit
exit

Script done on Mon 09 Mar 2015 05:04:27 PM PDT
