Script started on Mon 09 Mar 2015 05:08:08 PM PDT
[01;32mgyosh@gyosh-MBP[01;34m ~/Documents/rshell $[00m ls
[0m[01;34mbin[0m  LICENSE  Makefile  README.md  [01;34msrc[0m  [01;34mtests[0m
[01;32mgyosh@gyosh-MBP[01;34m ~/Documents/rshell $[00m bin/rshell
gyosh@gyosh-/home/gyosh/Documents/rshell$ ls
bin  LICENSE  Makefile	README.md  src	tests
gyosh@gyosh-/home/gyosh/Documents/rshell$ #oupt  tput redirection
gyosh@gyosh-/home/gyosh/Documents/rshell$ ls > test
gyosh@gyosh-/home/gyosh/Documents/rshell$ cat test
bin
LICENSE
Makefile
README.md
src
test
tests
gyosh@gyosh-/home/gyosh/Documents/rshell$ ls
bin  LICENSE  Makefile	README.md  src	test  tests
gyosh@gyosh-/home/gyosh/Documents/rshell$ ls    ##  appending
gyosh@gyosh-/home/gyosh/Documents/rshell$ ls >>      -l >> tests 
gyosh@gyosh-/home/gyosh/Documents/rshell$ ls
bin  LICENSE  Makefile	README.md  src	test  tests
gyosh@gyosh-/home/gyosh/Documents/rshell$ cat test
bin
LICENSE
Makefile
README.md
src
test
tests
total 44
drwxr-xr-x 2 gyosh gyosh  4096 Mar  9 17:06 bin
-rw-r--r-- 1 gyosh gyosh 18027 Feb  2 17:22 LICENSE
-rw-r--r-- 1 gyosh gyosh   224 Feb 23 00:10 Makefile
-rw-r--r-- 1 gyosh gyosh  1075 Feb 23 00:10 README.md
drwxr-xr-x 2 gyosh gyosh  4096 Mar  9 17:06 src
-rw-r--r-- 1 gyosh gyosh    46 Mar  9 17:08 test
drwxr-xr-x 2 gyosh gyosh  4096 Mar  9 17:08 tests
gyosh@gyosh-/home/gyosh/Documents/rshell$ #input redirection
gyosh@gyosh-/home/gyosh/Documents/rshell$ ls
bin  LICENSE  Makefile	README.md  src	test  tests
gyosh@gyosh-/home/gyosh/Documents/rshell$ grep a < test
Makefile
total 44
drwxr-xr-x 2 gyosh gyosh  4096 Mar  9 17:06 bin
-rw-r--r-- 1 gyosh gyosh   224 Feb 23 00:10 Makefile
drwxr-xr-x 2 gyosh gyosh  4096 Mar  9 17:06 src
-rw-r--r-- 1 gyosh gyosh    46 Mar  9 17:08 test
drwxr-xr-x 2 gyosh gyosh  4096 Mar  9 17:08 tests
gyosh@gyosh-/home/gyosh/Documents/rshell$ 	ls
bin  LICENSE  Makefile	README.md  src	test  tests
gyosh@gyosh-/home/gyosh/Documents/rshell$ # ls > test
gyosh@gyosh-/home/gyosh/Documents/rshell$ cat test
bin
LICENSE
Makefile
README.md
src
test
tests
gyosh@gyosh-/home/gyosh/Documents/rshell$ 			ls
bin  LICENSE  Makefile	README.md  src	test  tests
gyosh@gyosh-/home/gyosh/Documents/rshell$ grep a < nonex
open: No such file or directory
dup: Bad file descriptor
grep: (standard input): Bad file descriptor
gyosh@gyosh-/home/gyosh/Documents/rshell$ ls
bin  LICENSE  Makefile	README.md  src	test  tests
gyosh@gyosh-/home/gyosh/Documents/rshell$ exit
[01;32mgyosh@gyosh-MBP[01;34m ~/Documents/rshell $[00m exit
exit

Script done on Mon 09 Mar 2015 05:10:04 PM PDT
