Script started on Mon 09 Mar 2015 01:43:35 PM PDT
[01;32mgyosh@gyosh-MBP[01;34m ~/Documents/rshell $[00m ls
LICENSE  Makefile  README.md  [0m[01;34msrc[0m  [01;34mtests[0m
[01;32mgyosh@gyosh-MBP[01;34m ~/Documents/rshell $[00m pwd
/home/gyosh/Documents/rshell
[01;32mgyosh@gyosh-MBP[01;34m ~/Documents/rshell $[00m make
mkdir bin
g++ -std=c++11 src/rshell.cpp -o bin/rshell 
g++ -std=c++11 src/ls.cpp -o bin/ls 
[01;32mgyosh@gyosh-MBP[01;34m ~/Documents/rshell $[00m make clean
rm -r bin
[01;32mgyosh@gyosh-MBP[01;34m ~/Documents/rshell $[00m ls
LICENSE  Makefile  README.md  [0m[01;34msrc[0m  [01;34mtests[0m
[01;32mgyosh@gyosh-MBP[01;34m ~/Documents/rshell $[00m git chck[K[Keckout hw3
HEAD is now at e5f3d9e... basic I/O redirection added
[01;32mgyosh@gyosh-MBP[01;34m ~/Documents/rshell $[00m g[Kmake
mkdir bin
g++ -std=c++11 src/rshell.cpp -o bin/rshell 
g++ -std=c++11 src/ls.cpp -o bin/ls 
[01;32mgyosh@gyosh-MBP[01;34m ~/Documents/rshell $[00m m[Kls
[0m[01;34mbin[0m  LICENSE  Makefile  README.md  [01;34msrc[0m  [01;34mtests[0m
[01;32mgyosh@gyosh-MBP[01;34m ~/Documents/rshell $[00m bin/rshell
gyosh@gyosh-/home/gyosh/Documents/rshell$ ls
bin  LICENSE  Makefile	README.md  src	tests
gyosh@gyosh-/home/gyosh/Documents/rshell$ ls bin
ls  rshell
gyosh@gyosh-/home/gyosh/Documents/rshell$ which ls
/bin/ls
gyosh@gyosh-/home/gyosh/Documents/rshell$ #this will be gh th   the beginning of my testcases s
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
Aborted
[01;32mgyosh@gyosh-MBP[01;34m ~/Documents/rshell $[00m exit
exit

Script done on Mon 09 Mar 2015 01:45:00 PM PDT
